# Generated by Django 4.1.3 on 2024-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customuser_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_description',
            field=models.CharField(default='', max_length=400),
        ),
    ]
