# Generated by Django 4.1.3 on 2022-11-29 10:55

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20221030_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=store.models.upload_to, verbose_name='Image'),
        ),
    ]
