# Generated by Django 4.1.3 on 2022-11-29 11:56

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/default.png', upload_to=store.models.upload_to, verbose_name='Image'),
        ),
    ]
