# Generated by Django 4.1.3 on 2022-12-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_alter_product_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="images",),
    ]
