# Generated by Django 4.1.3 on 2022-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0036_remove_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="email",
            field=models.CharField(default="mo@gmai.com", max_length=120, unique=True),
        ),
    ]
