# Generated by Django 4.1.3 on 2022-12-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0037_product_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="email",
            field=models.CharField(default="mo@gmai.com", max_length=120),
        ),
    ]
