# Generated by Django 4.1.3 on 2022-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_alter_product_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="email",
            field=models.CharField(default="default@gmail.com", max_length=120),
        ),
    ]
