# Generated by Django 4.1.3 on 2022-12-04 11:20

from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0040_remove_product_image_product_userid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(
                default="products/default.png",
                upload_to=store.models.upload_to,
                verbose_name="Image",
            ),
        ),
    ]
